// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Porto.Data.DataContext;

namespace Porto.Data.Migrations
{
    [DbContext(typeof(PortoContext))]
    partial class PortoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Porto.Business.Model.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<string>("Cliente");

                    b.Property<string>("NroConteiner");

                    b.Property<string>("Status");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Porto.Business.Model.Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataFim");

                    b.Property<string>("DataInicio");

                    b.Property<string>("Navio");

                    b.Property<string>("TipoMovimento");

                    b.Property<int>("containerId");

                    b.HasKey("Id");

                    b.HasIndex("containerId");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("Porto.Business.Model.Movimento", b =>
                {
                    b.HasOne("Porto.Business.Model.Container", "Container")
                        .WithMany("Movimentos")
                        .HasForeignKey("containerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
